version: '3.7'

services:
  notificationsconsumer:
    image: notificationsconsumer
    build: ./notification-consumer
    environment:
      NODE_ENV: development
      MAX_SMS_COUNT_PER_SECOND: 10
      KAFKA_HOST: 'kafka:9092'
      REDIS_URL: 'redis://redisdb:6379'
      PORT: 80
    ports:
      - '8000:80'
    depends_on:
      - kafka
      - redisdb
    networks:
      - app-network

  notificationsproducer:
    image: notificationsproducer
    build: ./notification-publisher
    environment:
      NODE_ENV: development
      KAFKA_HOST: 'kafka:9092'
      PORT: 80
    ports:
      - '8080:80'
    depends_on:
      - kafka
      - redisdb
      - zookeeper
    networks:
      - app-network

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
    networks:
      - app-network
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER: DEBUG
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
  redisdb:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    networks:
      - app-network
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

networks:
  app-network:
    driver: bridge
